Repository EANsim/gecko, pull requests merged in 2024-02, with the labels that each got.

#10 Add main menu with working exit button
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src/App.svelte
  src/app.css
  src/assets/main_menu_background.jpg
Labels: enhancement

#12 Added easy to use build configs (vscode + rustrover)
  .eslintrc.json
  .gitignore
  .pre-commit-config.yaml
  .prettierrc
  .run/Run dev server.run.xml
  .run/Run tauri app.run.xml
  .run/Svelte check.run.xml
  .run/Trunk Serve.run.xml
  .run/Vite build.run.xml
  .run/Vite preview.run.xml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  Cargo.lock
  Cargo.toml
  README.md
  package-lock.json
  package.json
  src/App.svelte
  src/lib/Counter.svelte
  src/main.ts
Labels: enhancement

#13 Added more configuration to builds
  .editorconfig
  .eslintrc.json
  .pre-commit-config.yaml
  package-lock.json
  package.json
  src/App.svelte
  src/app.css
  src/assets/svelte.svg
  svelte.config.js
  vite.config.ts
Labels: bug, documentation, enhancement

#15 Added adequate pre-commit hooks for rust, fixed postcss parser warning
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prettierrc
  .run/Trunk Serve.run.xml
  .run/format-frontend.run.xml
  .run/lint-frontend.run.xml
  .run/run-dev-server.run.xml
  .run/run-dev-simulator-app.run.xml
  .run/run-simulator-backend.run.xml
  .run/simulator-build-debug.run.xml
  .run/svelte-check.run.xml
  .run/vite-build.run.xml
  .run/vite-preview.run.xml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  index.html
  package-lock.json
  package.json
  src-tauri/build.rs
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
  src/app.css
  src/lib/Counter.svelte
  src/lib/test_counter_lib.svelte
  src/main.ts
  src/main_menu.svelte
  tsconfig.json
  tsconfig.node.json
Labels: bug, enhancement
